export const CREATE_NEWUSER = "CREATE_NEWUSER";
export const UPDATE_NEWUSER = "UPDATE_NEWUSER";
export const SIGN_IN = "SIGN_IN";
export const UPDATE_GOALWEIGHT = "UPDATE_GOALWEIGHT";
export const UPDATE_WEIGHT = "UPDATE_WEIGHT";